config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users,:path=>'accounts'
  root 'posts#index'
  resources :relationships,only: [:create, :destroy]
  resources :users do
    
    member do
      get :following, :followers
    end

    get 'my_post' => 'posts#my_post', as: 'my_post'
    get 'show', to: 'profiles#show', as: :profile  

    resources :posts do
      resources :comments
      member do
      
      get 'like'
      get 'unlike'

      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_attached_file :image,
  					styles: {medium: '1000x1000>',thumb: '100x100',large: 'original'},
  					default_url: ':style/missing.png'
  validates_attachment_content_type :image,
  					content_type: ['image/jpeg','image/gif','image/png']
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  has_many :comments, dependent: :destroy
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/	

has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy


has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy


has_many :following, through: :active_relationships, source: :followed


has_many :followers, through: :passive_relationships, source: :follower





# Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  

  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:avatar])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
  end

 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post
def create
  @comment = @post.comments.build(comment_params)
  @comment.user_id = current_user.id
  if @comment.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  else
    flash[:alert] = "Check the comment form, something went wrong."
    render root_path
  end
end
def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user_id == current_user.id or @post.user==current_user
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
end
private
def comment_params  
  params.require(:comment).permit(:content)
end
def set_post  
  @post = Post.find(params[:post_id])
end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 10).order('id DESC') 
  end
  def current_user?(user)
    user ==current_user
    
  end
  def correct_user
    @user=User.find(params[:user_id])
    redirect_to(root_url) unless current_user?(@user)
    
  end
  def show  
  @post = Post.find(params[:id])
  end 
  def my_post
    
    @user=User.find(params[:user_id])
    @posts = @user.posts.paginate(:page => params[:page], :per_page => 10).order('id DESC')
    @post=Post.new
    
  end

	def new
    @user=User.find(params[:user_id])
    @post = Post.new
  	end

	def create  
  		@post = Post.create(post_params)
  		redirect_to user_posts_path
	end 
	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to :back	
		
	end
	def like	
		@post = Post.find(params[:id])
		if @post.liked_by current_user
	      respond_to do |format|
	        format.html { redirect_to :back }
	        format.js {}
	      end
    	end	
	end
	def unlike	
		@post = Post.find(params[:id]) 
		if @post.unliked_by current_user
	      respond_to do |format|
	        format.html { redirect_to :back }
	        format.js {}
	      end
    	end	
	end
	def edit
		@post = Post.find(params[:id])
		
	end
	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to root_url
		
	end

	private
	

	def post_params
		params.require(:post).permit(:image, :description, :user_id)
	end
	def set_post  
  		@post = Post.find(params[:post_id])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  	def show 
  		@user = User.find_by(name: params[:user_id])
  		#@user=User.find(params[:id]) 
  		#@posts = @user.posts.order('created_at DESC')
  		#@post=Post.new
  		@posts = User.find_by(name: params[:user_id]).posts.order('created_at DESC')
	end 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :user_signed_in?

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  def show
    @user=User.find(params[:id])
    @posts=@user.posts.order(created_at: :DESC)
  end


  private
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper 
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 2
    count_likers(votes)
  end 
  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end
  def list_likers(votes)
    user_names = []

    unless votes.blank?
      votes.voters.each do |voter|

        user_names.push(link_to voter.name,
                                user_path(voter),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end
  def liked_post(post)  
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end  

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
          <%if user_signed_in? %>
            <div class="user-name">
            <p class="round-image-50">
            <%= image_tag(comment.user.avatar.url(:thumb)) %></p>
              <%= link_to comment.user.name, user_path(comment.user) %>
            </div>
            <%end %>
            <div class="comment-content">
              <%= comment.content %>
              <div class="text-right">
                  <% if current_user== comment.user || post.user==current_user %>
                    <%= link_to user_post_comment_path(post.user,post, comment), method: :delete, data: { confirm: "Are you sure?" } ,remote: true do %>
                      <span class="glyphicon glyphicon-remove delete-comment"></span>
                    <% end %>
                  <% end %>
              </div>    
            </div>
          
       

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domashka41</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="navbar-nav navbar-right">
        
          <% if user_signed_in? %>
            <li class="navbar-text">
              Hello, <%= link_to truncate(current_user.name,length:9), edit_user_registration_path(current_user), class: 'navbar-link' %>
            </li>
            <li class="navbar-text">
              <%= link_to 'New Post', new_user_post_path(current_user), class: 'navbar-link' %>
            </li>
            <li class="navbar-text">
              <%= link_to '',user_my_post_path(current_user),class:"glyphicon glyphicon-user navbar-link" %>
            </li>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><%= link_to 'My profile',user_my_post_path(current_user) %> </a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% else %>
            <%= link_to 'Register', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </ul>
      
    </div>
  </div>
</nav>


      
<%= yield %>


</body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
<%= form_for [current_user, @post], html: {class: 'form-horizontal'} do |f| %>

  <div class="form-group text-center">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="form-group text-center">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/posts/_likes.html.erb
<div class="likes",id="likes_<%= post.id%>">
  <%= display_likes post %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= will_paginate @posts %>
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
  <div class="post">
    <div class="post-head">
    <%#if @user==user_signed_in? %>
      <div class="user-name">
          <%= link_to post.user.name, user_path(post.user) %>
      </div>
      <%#end %>
    </div>
    <div class="time-ago text-center">
    <%a = (Time.now-post.created_at).to_i%>
    <%=case a 
      when 0 then 'just now'
      when 1 then 'a second ago'
      when 2..59 then a.to_s+' seconds ago' 
      when 60..119 then 'a minute ago' #120 = 2 minutes
      when 120..3540 then (a/60).to_i.to_s+' minutes ago'
      when 3541..7100 then 'an hour ago' # 3600 = 1 hour
      when 7101..82800 then ((a+99)/3600).to_i.to_s+' hours ago' 
      when 82801..172000 then 'a day ago' # 86400 = 1 day
      when 172001..518400 then ((a+800)/(60*60*24)).to_i.to_s+' days ago'
      when 518400..1036800 then 'a week ago'
      else ((a+180000)/(60*60*24*7)).to_i.to_s+' weeks ago'
    end 
    %>

    
      
      <%#= time_ago_in_words post.created_at %>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), user_post_path(post.user,post) %>
    </div>
    <div class="post-bottom">
      
        <%= render 'posts/likes', post: post %>
      
    </div>
    <p class="caption">
      <%= post.description %><br>	
    </p>
    <div class="comments" id="comments_<%= post.id %>">
      <% if post.comments %>
      <div class="comment">
        <%= render post.comments, post: post %>
      </div>
      <% end %>
    </div>
    <div class="comment-like-form row">
    <%if user_signed_in? %>
    <%if current_user.liked? post %>
      <div class="col-sm-1">
          <%= link_to '', unlike_user_post_path(post.user.id,post.id), method: :get, remote: true,class:"glyphicon #{liked_post post}",id: "like_#{post.id}"%>
      </div>
      <%else %>
      <div class="col-sm-1">
          <%= link_to '', like_user_post_path(post.user.id,post.id), method: :get, remote: true,class:"glyphicon #{liked_post post}",id: "like_#{post.id}"%>
      </div>
      <%end %>
      <%end %>
      
      <div class="comment-form col-sm-11">
        <%= form_for([post.user,post, post.comments.build], remote: true) do |f| %>

          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"%>
        <% end %>
      </div> 
    </div>
  </div>
  <% end %>
</div>

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');

$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/my_post.html.erb
<%= will_paginate @posts %>
<div class="posts-wrapper row">
  <section class="stats">
    <%= render 'shared/stats' %>
    posts <%= @posts.size %>
  </section>
  <% @posts.each do |post| %>
    <div class="post">

      <div class="post-head">
        <div class="name">
          <h6><%= link_to post.user.name, user_path(post.user) %><br></h6>
        </div>
      </div>

      <div class="image center-block">
        <%= image_tag post.image.url(:medium), class:'img-responsive' %>  
      </div>

      <p class="caption">
        <%= post.description %><br> 
      </p>

      <p>
        <%if current_user == @user%>
          <%= link_to 'Edit',edit_user_post_path(post.user,post) %>
          <%= link_to 'Delete', user_post_path(post.user,post),
            method: :delete,
            data: {confirm: 'Do you want to remove this product?'} %>
        <%end %> 
      </p>

      <div class="post-bottom">
        <%= render 'posts/likes', post: post %>   
      </div>

      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments %>

          <div class="comment">
            <%= render post.comments, post: post %>
          </div>
        <% end %>
      </div>

      <div class="comment-like-form row">
        <%if user_signed_in? %>
          <%if current_user.liked? post %>
            <div class="col-sm-1">
                <%= link_to '', unlike_user_post_path(post.user.id,post.id), method: :get, remote: true,class:"glyphicon #{liked_post post}",id: "like_#{post.id}"%>
            </div>
          <%else %>
            <div class="col-sm-1">
                <%= link_to '', like_user_post_path(post.user.id,post.id), method: :get, remote: true,class:"glyphicon #{liked_post post}",id: "like_#{post.id}"%>
            </div>
          <%end %>
        <%end %> 
        <div class="comment-form col-sm-11">
          <%= form_for([post.user,post, post.comments.build], remote: true) do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"%>
            <% end %>
        </div> 
      </div>
    </div>
  <% end %>
</div>





    

  

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        <%= @post.user.name %><br>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:large) %>
    </div>
    <p class="caption">
      <%= @post.description %>
    </p>
    <div class="text-center">
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');

$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/profiles/show.html.erb
 
<% @posts.each do |post| %>
  <%#= render 'posts/post', post: post %>
  <div class="post">
      <div class="post-head">
        <div class="name">
          <h6><%= post.user.name %> <br></h6>
          <p class="round-image-50"><%= image_tag(post.user.avatar.url(:thumb)) %></p>
          <%if @user == current_user%>
          <%= link_to 'Edit profile', edit_user_registration_path(current_user) %>
           <%end %> 
        </div>
      </div>
      <div class="image center-block">
      <%= image_tag post.image.url(:medium), class:'img-responsive' %>
        
      </div>
      <p class="caption">
        <%= post.description %><br> 
      </p>
      <p>
        <%if @user == current_user%>
              <%= link_to 'Edit',edit_user_post_path(post.user,post) %>
              <%= link_to 'Delete', user_post_path(post.user,post),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
                 <%end %> 
      </p>
    </div>
  <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user==@user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/show.html.erb
 
<% @posts.each do |post| %>
  <%#= render 'posts/post', post: post %>
  <div class="post">
      <div class="post-head">
        <div class="name">
          <h6><%= post.user.name %> <br></h6>
	          <section class="stats">
	      		<%= render 'shared/stats' %>
	    	  </section>
	    	  <%= render 'follow_form' if user_signed_in? %>
          <p class="round-image-50"><%= image_tag(post.user.avatar.url(:medium)) %></p>
          <%if @user == current_user%>
          <%= link_to 'Edit profile', edit_user_registration_path(current_user) %>
           <%end %> 
        </div>
      </div>
      <div class="image center-block">
      <%= image_tag post.image.url(:medium), class:'img-responsive' %>
        
      </div>
      <p class="caption">
        <%= post.description %><br> 
      </p>
      <p>
        <%if @user == current_user%>
              <%= link_to 'Edit',edit_user_post_path(post.user,post) %>
              <%= link_to 'Delete', user_post_path(post.user,post),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
                 <%end %> 
      </p>
    </div>
  <% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <div class="follow-avatar">
        <%= link_to image_tag(@user.avatar.url(:thumb)), user_path(@user), class: 'image-responsive' %>
      </div>
      <span><b>Posts:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
    <% @users.each do |user| %>
    <div class="col-sm-3">
      <ul class="users follow">
        <li>
        <%= link_to user.name, user_path(user) %>
        <%= link_to image_tag(user.avatar.url(:thumb)), user_path(user), class: 'image-responsive' %>
        </li>
      </ul>
    </div>
        <% end %>
    <% end %>
  </div>